//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bayiler
    {
        public int BayiID { get; set; }
        public string BayiKod { get; set; }
        public string BayiUnvan { get; set; }
        public decimal BayiBakiye { get; set; }
        public string BayiYetkiliKisi { get; set; }
        public string BayiSifre { get; set; }
    }
}
