//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int KullaniciID { get; set; }
        public int KullaniciGrup { get; set; }
        public int KullaniciBayiId { get; set; }
        public string KullaniciAdi { get; set; }
        public string KullaniciMail { get; set; }
        public string KullaniciSifre { get; set; }
    }
}
