//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisKart
    {
        public int SiparisKartID { get; set; }
        public Nullable<int> bayiID { get; set; }
        public string bayiKod { get; set; }
        public string bayiUnvan { get; set; }
        public Nullable<decimal> SiparisKartTutar { get; set; }
        public Nullable<System.DateTime> SiparisKartTarih { get; set; }
    }
}
